// Keys generated by /usr/local/bin/curve_keygen

var zmqSidKeys = {
  DEV: '7f188e5244b02bf497b86de417515cf4d4053ce4eb977aee91a55354655ec33a',
  PRD: '7f188e5244b02bf497b86de417515cf4d4053ce4eb977aee91a55354655ec33a'
};

exports.lookupSidKey = function(sid) {
  return new Buffer(zmqSidKeys[sid], 'hex');
};
